### ISSUE TITLE
Bug: Release generation

### ISSUE THREAD

**Issue by danny248** [InQuest/ThreatKB#137]
threatkb_1  | Traceback (most recent call last):
threatkb_1  |   File "/opt/threatkb/env/local/lib/python2.7/site-packages/flask/app.py", line 1358, in full_dispatch_request
threatkb_1  |     rv = self.dispatch_request()
threatkb_1  |   File "/opt/threatkb/env/local/lib/python2.7/site-packages/flask/app.py", line 1344, in dispatch_request
threatkb_1  |     return self.view_functions[rule.endpoint](**req.view_args)
threatkb_1  |   File "/opt/threatkb/env/local/lib/python2.7/site-packages/flask_login/utils.py", line 228, in decorated_view
threatkb_1  |     return func(*args, **kwargs)
threatkb_1  |   File "/opt/threatkb/app/__init__.py", line 32, in wrapped
threatkb_1  |     return f(*args, **kwargs)
threatkb_1  |   File "/opt/threatkb/app/routes/releases.py", line 61, in generate_release_notes
threatkb_1  |     content = entity.generate_release_notes()
threatkb_1  |   File "/opt/threatkb/app/models/releases.py", line 132, in generate_release_notes
threatkb_1  |     len(self.release_data_dict["Signatures"]["Added"]) > 0 else "NA"
threatkb_1  | TypeError: string indices must be integers
threatkb_1  | 172.20.0.1 - - [07/Nov/2017 06:51:05] "GET /ThreatKB/releases/1/release_notes HTTP/1.0" 500 -

**Comment by danny248** [comment]
d5118d58c24df61c51b092a9ce37f2bd4f9796e2
