### ISSUE TITLE
Unable to start the container - using the docker compose

### ISSUE THREAD

**Issue by horialex** [InQuest/ThreatKB#378]
I am unable to start the contiainer using the docker compse up command
I followed the docker instalation guide 
Build the image and than docker compose up
My OS is ubuntu 18.04 - fresh install - no other containers on pc

![image](https://user-images.githubusercontent.com/7558006/79485709-5c0dbd80-801e-11ea-8244-8df3f7f549cd.png)

**Comment by pedramamini** [comment]
@horialex first and foremost... thanks for your interest. Second, ThreatKB, while we use it in production today, is super ALPHA state. Caveats aside, if you want to give it a shot, try the staging branch (not master) and let us know if you experience the same issue.

**Comment by horialex** [comment]
Thanks I appreciate the help, I hope it works I will try it next week

**Comment by horialex** [comment]
hello, I tried with staging branch but still not working

**Comment by pedramamini** [comment]
Could you describe what problem you had? Share any relevant screenshots and error messages.

**Comment by horialex** [comment]
So i followed the steps from docker installation steps and the outcome was the following:
I will put a few screenshots with the steps that i took and with the output:

**Branch used**
![Branch](https://user-images.githubusercontent.com/7558006/80180613-d4bade00-860b-11ea-9131-93acd2fb8604.png)

**docker install
![Install1](https://user-images.githubusercontent.com/7558006/80180642-e4d2bd80-860b-11ea-8f2b-2d68f27a45d8.png)
**

**install problems**

![Prob1](https://user-images.githubusercontent.com/7558006/80180778-23687800-860c-11ea-85fd-9ee0a4f024e3.png)

![Prob2](https://user-images.githubusercontent.com/7558006/80180783-26fbff00-860c-11ea-92a2-67462422c651.png)

![Prob3](https://user-images.githubusercontent.com/7558006/80180790-2a8f8600-860c-11ea-8179-c14c6ee5f64d.png)

![Prob4](https://user-images.githubusercontent.com/7558006/80180796-2d8a7680-860c-11ea-8b7f-6cd23f93c757.png)

**finish install**
![finish install](https://user-images.githubusercontent.com/7558006/80180804-324f2a80-860c-11ea-83c6-2d475e6f9855.png)

**composer up**
![composer start](https://user-images.githubusercontent.com/7558006/80180835-485ceb00-860c-11ea-8fe9-c13870e5af32.png)

**composer error**

![composer error](https://user-images.githubusercontent.com/7558006/80180864-5c085180-860c-11ea-8043-806265e9f2e1.png)


**composer output** -I have attached a zip containing the output of the composer step
it is archived because it didn't allowed me to put a text file in the comments

[Composert command line output.zip](https://github.com/InQuest/ThreatKB/files/4527007/Composert.command.line.output.zip)


**URL error when opening the suggested link**

![URL error](https://user-images.githubusercontent.com/7558006/80180967-983bb200-860c-11ea-943e-901e3b19f621.png)

**Comment by horialex** [comment]
can you please help me on this?

**Comment by dcuellar322** [comment]
@danny248 Fixed...please review as there changes to `Dockerfile` like Ubuntu version, etc. https://github.com/InQuest/ThreatKB/pull/386

**Comment by horialex** [comment]
I will try it, but at the moment I am very sick and I can't work on it.
Thanks for the effort anyway I appreciate it.

**Comment by horialex** [comment]
Hello, I resumed my work, I tried both with master and staging branches but I ended up with the same problem as above, I used docker instalation. 
Is there another branch were it was fixed or am I missing something out?

**Comment by horialex** [comment]
Actually not the same error, I tried on the brach with the fix but i received:
db_1              | 2020-11-07T11:46:39.166084Z 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
db_1              | 2020-11-07T11:46:39.167981Z 0 [ERROR] --initialize specified but the data directory has files in it. Aborting.
db_1              | 2020-11-07T11:46:39.168056Z 0 [ERROR] Aborting

**Comment by horialex** [comment]
Hello, I tried using it on the issue branch and i managed to start the containers but I have an UI problem
pid: 66|app: 0|req: 1/1] 172.20.0.1 () {36 vars in 570 bytes} [Sun Nov  8 07:45:53 2020] GET / => generated 12635 bytes in 16 msecs via sendfile() (HTTP/1.1 200) 8 headers in 304 bytes (0 switches on core 0)
[pid: 63|app: 0|req: 1/2] 172.20.0.1 () {36 vars in 587 bytes} [Sun Nov  8 07:45:54 2020] GET /lib/bootstrap-css/css/bootstrap.css => generated 146010 bytes in 18 msecs via sendfile() (HTTP/1.1 200) 8 headers in 305 bytes (0 switches on core 0)
[2020-11-08 07:45:54,136] ERROR in error_handling: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/flask/helpers.py", line 1082, in send_static_file
    self.static_folder, filename, cache_timeout=cache_timeout
  File "/usr/local/lib/python2.7/dist-packages/flask/helpers.py", line 767, in send_from_directory
    raise NotFound()
NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/flask/helpers.py", line 1082, in send_static_file
    self.static_folder, filename, cache_timeout=cache_timeout
  File "/usr/local/lib/python2.7/dist-packages/flask/helpers.py", line 767, in send_from_directory
    raise NotFound()
NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
[2020-11-08 07:45:54,215] ERROR in app: Exception on /lib/angular-bootstrap/ui-bootstrap-csp.css [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1815, in handle_user_exception
    return self.handle_http_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1743, in handle_http_exception
    return handler(e)
  File "/opt/threatkb/app/routes/error_handling.py", line 31, in handle_exception
    user_id=current_user.id,
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/local.py", line 348, in __getattr__
    return getattr(self._get_current_object(), name)
AttributeError: 'AnonymousUserMixin' object has no attribute 'id'
Exception on /lib/angular-bootstrap/ui-bootstrap-csp.css [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1815, in handle_user_exception
    return self.handle_http_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1743, in handle_http_exception
    return handler(e)
  File "/opt/threatkb/app/routes/error_handling.py", line 31, in handle_exception
    user_id=current_user.id,
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/local.py", line 348, in __getattr__
    return getattr(self._get_current_object(), name)
AttributeError: 'AnonymousUserMixin' object has no attribute 'id'
[2020-11-08 07:45:54,228] ERROR in error_handling: 500 error message '500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.'
500 error message '500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.'

**Comment by horialex** [comment]
It seems that I can't access this file : 
http://127.0.0.1:5000/lib/angular-bootstrap/ui-bootstrap-csp.css 

500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

**Comment by azazelm3dj3d** [comment]
This issue should now be resolved under the [rc branch](https://github.com/InQuest/ThreatKB/tree/rc).
