### ISSUE TITLE
Failure to build Docker image

### ISSUE THREAD

**Issue by dspruell-s01** [InQuest/ThreatKB#392]
Referencing https://github.com/InQuest/ThreatKB/blob/master/wiki/docker.md

Running this command to build the image fails after several minutes:

    docker build -t threatkb

Build log here:

https://gist.github.com/dspruell-s01/0ced46956e8e1634b6b15e0f0e26c28a

Immediate stack trace in installing bcrypt module:

```
#11 40.48 Collecting bcrypt (from Flask-Bcrypt==0.7.1->-r requirements.txt (line 22))
#11 40.73   Downloading https://files.pythonhosted.org/packages/d8/ba/21c475ead997ee21502d30f76fd93ad8d5858d19a3fad7cd153de698c4dd/bcrypt-3.2.0.tar.gz (42kB)
#11 41.15     Complete output from command python setup.py egg_info:
#11 41.15     Couldn't find index page for 'cffi' (maybe misspelled?)
#11 41.15     No local packages or download links found for cffi>=1.1
#11 41.15     Traceback (most recent call last):
#11 41.15       File "<string>", line 1, in <module>
#11 41.15       File "/tmp/pip-build-i8v7Th/bcrypt/setup.py", line 76, in <module>
#11 41.15         cmdclass={"test": PyTest},
#11 41.15       File "/usr/lib/python2.7/distutils/core.py", line 111, in setup
#11 41.15         _setup_distribution = dist = klass(attrs)
#11 41.15       File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 269, in __init__
#11 41.15         self.fetch_build_eggs(attrs['setup_requires'])
#11 41.15       File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 313, in fetch_build_eggs
#11 41.15         replace_conflicting=True,
#11 41.15       File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 826, in resolve
#11 41.15         dist = best[req.key] = env.best_match(req, ws, installer)
#11 41.15       File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1092, in best_match
#11 41.15         return self.obtain(req, installer)
#11 41.15       File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1104, in obtain
#11 41.15         return installer(requirement)
#11 41.15       File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 380, in fetch_build_egg
#11 41.15         return cmd.easy_install(req)
#11 41.15       File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 657, in easy_install
#11 41.15         raise DistutilsError(msg)
#11 41.15     distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('cffi>=1.1')
#11 41.15     
#11 41.15     ----------------------------------------
#11 41.34 Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-i8v7Th/bcrypt/
#11 41.46 You are using pip version 8.1.1, however version 21.2.2 is available.
#11 41.46 You should consider upgrading via the 'pip install --upgrade pip' command.
------
executor failed running [/bin/sh -c pip install --upgrade pip & pip install virtualenv && pip install -r requirements.txt]: exit code: 1
```

**Comment by azazelm3dj3d** [comment]
This issue is now resolved under the [rc branch](https://github.com/InQuest/ThreatKB/tree/rc). Following the [Docker Installation wiki](https://github.com/InQuest/ThreatKB/wiki/Docker) instructions should now work.
