### ISSUE TITLE
Server error in ThreatKB API from Recorded Future integration script

### ISSUE THREAD

**Issue by dspruell-i01** [InQuest/ThreatKB#500]
Start of conversation in Slack:

https://inquestdotnet.slack.com/archives/C010384MEK1/p1720628302683899

### Client side context
A client-side script (`rf_to_threatkb.py`) inserts a subset of indicators from Recorded Future to ThreatKB C2 (IPs, domains). It looks to have encountered a 500 error from the server due to a data encoding error:

```<title>The page is temporarily unavailable</title>

                    <p>Something has triggered an error on your
                    website.  This is the default error page for
                    <strong>nginx</strong> that is distributed with
                    Fedora.  It is located
                    <tt>/usr/share/nginx/html/50x.html</tt></p>
```

Client-side traceback:

```
Traceback (most recent call last):
  File "./bin/rf_to_threatkb.py", line 95, in <module>
    tkb_rf_indicators  = utils.intel.recorded_future_indicators()
  File "/opt/research/venv3/lib/python3.6/site-packages/utils/cloud.py", line 570, in wrapper
    result = f(*args, **kwargs)
  File "/opt/research/venv3/lib/python3.6/site-packages/utils/intel.py", line 708, in recorded_future_indicators
    results = threatkb_wrap_retry(THREATKB.search, [options])
  File "/opt/research/venv3/lib/python3.6/site-packages/utils/intel.py", line 1385, in threatkb_wrap_retry
    raise e
  File "/opt/research/venv3/lib/python3.6/site-packages/utils/intel.py", line 1381, in threatkb_wrap_retry
    return json.loads(data)
  File "/usr/local/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

Seems like an uncaught error in the client script as a result of the 500 response from the server.

### Server side context

We don't have any debugging or error information on hand from the server, but in theory any 500 errors from the ThreatKB API are likely to be related. More specifically, from any rule import endpoint, and more specifically, originating from the kb server as a client.

**Comment by dspruell-i01** [comment]
Another occurrence, possibly the same or related. The below is the view from the client side, i.e. the script running on kb server that interfaces with the ThreatKB API. This will likely correspond to 500 errors in ThreatKB.

```
[pedram@kb]$

# become research user
[pedram@kb]$ r
Last login: Wed Jul 24 05:00:01 UTC 2024

# run script manually and see it blow up
(venv3) [research@kb ~]$ ./bin/rf_to_threatkb.py
[2024-07-24T19:18:21.719391] rf_to_threatkb 20661 INFO retrieving indicators from RF...
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
    <head>
        <title>The page is temporarily unavailable</title>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <style type="text/css">
            /*<![CDATA[*/
            body {
                background-color: #fff;
                color: #000;
                font-size: 0.9em;
                font-family: sans-serif,helvetica;
                margin: 0;
                padding: 0;
            }
```
